version: 3
jobs:
  lint:
    docker:
      - image: circleci/rust:buster
    steps:
      - checkout
      - run:
          name: Version Information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install Rust Components
          command: rustup component add rustfmt clippy
      - run:
          name: Component Version Information
          command: cargo fmt -- --version; cargo clippy -- --version
      - run:
          name: Setup Env
          command: |
            echo 'export RUSTFLAGS="-D warnings"' >> $BASH_ENV
      - run:
          name: Lint (rustfmt)
          command: |
            cargo fmt -- --check
      - run:
          name: Lint (clippy)
          command: |
            cargo clippy --all-features
  build:
    docker:
      - image: circleci/rust:buster
    steps:
      - checkout
      - run:
          name: Setup Additional Languages
          command: |
            sudo apt-get update && sudo apt-get upgrade -y
            sudo apt-get install python3-all-dev python3-numpy
      - run:
          name: Version Information
          command: rustc --version; cargo --version; rustup --version; python3 --version
      - run:
          name: Setup Env
          command: |
            echo 'export RUSTFLAGS="-D warnings"' >> $BASH_ENV
      - run:
          name: Build and Test
          # Build all targets to ensure examples are built as well.
          command: |
            cargo build --all-targets --all-features
            cargo test --all-features

  # docs-build and docs-deploy are adapted from
  # https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/.
  docs-build:
    docker:
      - image: circleci/rust:buster
    steps:
      - checkout
      - run:
          name: Version Information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Generate documentation
          command: |
            cargo doc --all-features
      - persist_to_workspace:
          root: target
          paths: doc

workflows:
  version: 2
  build:
    jobs:
      - lint
      - build
      - docs-build
